image: node:lts

cache:
  paths:
  - dist

stages:
  - build
  - upload

build:
  stage: build
  script:
    - npm ci
    - npx ng build --prod

.upload_template: &upload_template
  stage: upload
  script:
    - mkdir -p ~/.ssh
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - scp  -r dist/piggytracker-frontend-angular/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

upload-prod:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PROD
  only:
    - tags

upload-preview:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PREVIEW
  only:
    refs:
      - dev
